### PR TITLE
for #2: add sensors, battery, webrtc variations

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
@gregglind - it can't be this easy can it?

This is a study with 6 variations of preference values and a 'nochanges' variation for control.

**Comment by gregglind** [comment]
Yes, it really is that easy :)

That's kind of why we have a library for this :)

**Comment by groovecoder** [comment]
@gregglind This branch has all of these variations in a single study:
- `nochanges`
- `sensors-disabled`
- `battery-disabled`
- `webrtc-default-only`
- `sensors-and-battery-disabled`
- `sensors-disabled-and-webrtc-default-only`
- `battery-disabled-and-webrtc-default-only`
- `sensors-disabled-battery-disabled-and-webrtc-default-only`

On IRC, you promised to elaborate on "the power to detect" results when studying this many variations at once.

**Comment by gregglind** [comment]
Fwiw, if you are thinking of doing a 'generate all combos' I would prefer to see it be programmatic using some 'n choose r' (combinations) algorithm :)   I can't guarantee you got them all.

**Comment by gregglind** [comment]
## Uncontroversial things:
1.  Assigning people to an arm with any number of prefs on
2.  Observing which 'combination' did the best.  

The problem:
- the error bars around each of those group outcomes is going to be awfully wide.

## Exegesis: Too many groups, not enough flavor

So, for 6 settings, where people can have any number of them on, in any combo, there will be `2^^6` or 64 groups.  

Suppose we had 2 groups, each of which had N people.  if we split those same people `(2*N)` into 64 groups, we would have `(2*N/64)` in each group.  Correspondingly, the CONFIDENCE INTERVALS in that setting would be `(sqrt 32)` wider, or `5.6 x` was wide.  

So, even if we observe _some best_ group, we will be hard pressed to know it's really better, both due to CONFIDENCE intervals, AND due to doing multiple comparison.

What's worse is that inside all those combinations the stories and orderings might not make sense.

## where does this leave us?

In an AI context, where we really don't care HOW things work, maybe _just pick the best one_ is okay.  But it's cargo-culty, and not repeatable. 

In an inference context... we _hope_ that this will _explain_ something, so we can feel confident that the model will be repeatable.

**Comment by groovecoder** [comment]
Closing in favor of exploring [referrer config changes](https://public.etherpad-mozilla.org/p/referrerimprovements).

**Pull request closed without merging**
